//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml;
using System.Xml.Serialization;


namespace NSLaserCfg {

    [XmlRoot()]
    public partial class MarkingTaskGroup {
        [XmlElement("IsActive")]
        public string _isActive;
        [XmlElement("IsStartUp")]
        public string _isStartUp;
        [XmlElement("IsEndAutorun")]
        public string _isEndAutorun;
        [XmlElement("IsFalseAutorun")]
        public string _isFalseAutorun;
        [XmlElement("LoadGroupOnEnd")]
        public string _loadGroupOnEnd;
        [XmlElement("LoadGroupOnFalse")]
        public string _loadGroupOnFalse;
        [XmlElement("Name")]
        public string _name;
        [XmlElement("Description")]
        public string _description;
        [XmlElement("ButtonStateAtRun")]
        public string _buttonStateAtRun;
        [XmlElement("TasksToRun")]
        public string _tasksToRun;
    }
}

